import { User, Email, CalendarEvent, Event, Vendor, Task } from './types';

export const USERS: User[] = [
  {
    id: 'user-1',
    name: 'You',
    email: 'you@example.com',
    role: 'owner',
  },
  {
    id: 'user-2',
    name: 'Partner',
    email: 'partner@example.com',
    role: 'partner',
  },
];

export const EMAILS: Email[] = [
  {
    id: 'email-1',
    userId: 'user-1',
    from: 'john@company.com',
    to: ['you@example.com'],
    subject: 'Project Update - Q2 Goals',
    body: 'Hi, here are the Q2 goals we discussed...',
    timestamp: new Date('2024-05-15T10:30:00'),
    read: false,
    starred: true,
  },
  {
    id: 'email-2',
    userId: 'user-1',
    from: 'sarah@company.com',
    to: ['you@example.com'],
    cc: ['team@company.com'],
    subject: 'Team Meeting Tomorrow at 2 PM',
    body: 'Please join us tomorrow for our weekly sync...',
    timestamp: new Date('2024-05-15T09:15:00'),
    read: true,
    starred: false,
  },
  {
    id: 'email-3',
    userId: 'user-1',
    from: 'news@newsletter.com',
    to: ['you@example.com'],
    subject: 'This Week\'s Tech News Digest',
    body: 'Here are the top tech stories from this week...',
    timestamp: new Date('2024-05-14T08:00:00'),
    read: true,
    starred: false,
  },
  {
    id: 'email-4',
    userId: 'user-1',
    from: 'admin@company.com',
    to: ['you@example.com'],
    subject: 'Workspace Update: New Features Released',
    body: 'We\'re excited to announce new features...',
    timestamp: new Date('2024-05-14T14:45:00'),
    read: false,
    starred: false,
  },
  {
    id: 'email-5',
    userId: 'user-1',
    from: 'conference@techconf.com',
    to: ['you@example.com'],
    subject: 'Early Bird Tickets - 30% Off This Week',
    body: 'Register for Tech Conference 2024...',
    timestamp: new Date('2024-05-13T11:20:00'),
    read: true,
    starred: false,
  },
  {
    id: 'email-6',
    userId: 'user-2',
    from: 'client@acme.com',
    to: ['partner@example.com'],
    subject: 'Re: Contract Review',
    body: 'Thank you for your review. We have a few questions...',
    timestamp: new Date('2024-05-15T11:00:00'),
    read: false,
    starred: true,
  },
  {
    id: 'email-7',
    userId: 'user-2',
    from: 'events@venue.com',
    to: ['partner@example.com'],
    subject: 'Venue Confirmation - Event on June 15th',
    body: 'Your venue booking is confirmed for June 15th at 6 PM...',
    timestamp: new Date('2024-05-15T10:00:00'),
    read: true,
    starred: true,
  },
  {
    id: 'email-8',
    userId: 'user-2',
    from: 'ceo@company.com',
    to: ['partner@example.com'],
    subject: 'Executive Meeting - Next Steps',
    body: 'Following up on our meeting yesterday...',
    timestamp: new Date('2024-05-14T16:30:00'),
    read: false,
    starred: false,
  },
];

export const CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'cal-1',
    userId: 'user-1',
    title: 'Team Standup',
    description: 'Daily 15-minute sync with the team',
    startTime: new Date('2024-05-16T10:00:00'),
    endTime: new Date('2024-05-16T10:15:00'),
    location: 'Conference Room A',
  },
  {
    id: 'cal-2',
    userId: 'user-1',
    title: 'Client Presentation',
    description: 'Q2 Results presentation to stakeholders',
    startTime: new Date('2024-05-17T14:00:00'),
    endTime: new Date('2024-05-17T15:30:00'),
    location: 'Main Office - Boardroom',
  },
  {
    id: 'cal-3',
    userId: 'user-1',
    title: 'One-on-One with Manager',
    description: 'Monthly check-in and goal review',
    startTime: new Date('2024-05-20T11:00:00'),
    endTime: new Date('2024-05-20T11:45:00'),
    location: 'Manager\'s Office',
  },
  {
    id: 'cal-4',
    userId: 'user-2',
    title: 'Executive Briefing',
    description: 'Board briefing on company strategy',
    startTime: new Date('2024-05-17T09:00:00'),
    endTime: new Date('2024-05-17T10:00:00'),
    location: 'Executive Suite',
  },
  {
    id: 'cal-5',
    userId: 'user-2',
    title: 'Gala Dinner Planning',
    description: 'Final review of arrangements for June 15th gala',
    startTime: new Date('2024-05-18T15:00:00'),
    endTime: new Date('2024-05-18T16:30:00'),
    location: 'Partner\'s Office',
  },
];

export const EVENTS: Event[] = [
  {
    id: 'event-1',
    title: 'Annual Gala Dinner',
    description: 'Formal black-tie event celebrating company milestones',
    date: new Date('2024-06-15'),
    location: 'Grand Ballroom, Downtown Hotel',
    organizer: 'Partner',
    guests: [
      {
        id: 'guest-1',
        name: 'John Smith',
        email: 'john.smith@company.com',
        rsvpStatus: 'accepted',
      },
      {
        id: 'guest-2',
        name: 'Sarah Johnson',
        email: 'sarah.j@company.com',
        rsvpStatus: 'accepted',
        dietaryRestrictions: 'Vegetarian',
      },
      {
        id: 'guest-3',
        name: 'Michael Chen',
        email: 'mchen@company.com',
        rsvpStatus: 'pending',
      },
      {
        id: 'guest-4',
        name: 'Amanda Williams',
        email: 'awilliams@company.com',
        rsvpStatus: 'declined',
      },
    ],
    checklists: [
      {
        id: 'checklist-1',
        title: 'Pre-Event Setup',
        dueDate: new Date('2024-06-14'),
        items: [
          {
            id: 'item-1',
            text: 'Confirm final headcount with catering',
            completed: true,
            assignee: 'Partner',
          },
          {
            id: 'item-2',
            text: 'Order floral arrangements',
            completed: true,
            assignee: 'Partner',
          },
          {
            id: 'item-3',
            text: 'Print seating chart',
            completed: false,
            assignee: 'Partner',
          },
        ],
      },
      {
        id: 'checklist-2',
        title: 'Day-Of Coordination',
        dueDate: new Date('2024-06-15'),
        items: [
          {
            id: 'item-4',
            text: 'Arrive early for setup',
            completed: false,
            assignee: 'Partner',
          },
          {
            id: 'item-5',
            text: 'Welcome remarks prepared',
            completed: true,
            assignee: 'Partner',
          },
        ],
      },
    ],
    notes: 'Budget: $25,000. Expect 80-100 guests. VIP table reserved for board members.',
  },
  {
    id: 'event-2',
    title: 'Executive Retreat - Team Building',
    description: 'Two-day off-site for leadership team',
    date: new Date('2024-07-10'),
    location: 'Mountain Lodge, Lake Tahoe',
    organizer: 'Partner',
    guests: [
      {
        id: 'guest-5',
        name: 'David Martinez',
        email: 'dmartinez@company.com',
        rsvpStatus: 'accepted',
      },
      {
        id: 'guest-6',
        name: 'Lisa Park',
        email: 'lpark@company.com',
        rsvpStatus: 'tentative',
        dietaryRestrictions: 'Gluten-free',
      },
    ],
    checklists: [
      {
        id: 'checklist-3',
        title: 'Logistics',
        dueDate: new Date('2024-07-05'),
        items: [
          {
            id: 'item-6',
            text: 'Book accommodations',
            completed: true,
            assignee: 'Partner',
          },
          {
            id: 'item-7',
            text: 'Arrange transportation',
            completed: false,
            assignee: 'Partner',
          },
        ],
      },
    ],
    notes: 'Budget: $15,000. Activities: team building exercises, executive workshops, dinner reception.',
  },
];

export const VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'Elegant Catering Co.',
    category: 'catering',
    contactPerson: 'Chef Marcus',
    email: 'marcus@elegantcatering.com',
    phone: '(555) 123-4567',
    website: 'www.elegantcatering.com',
    serviceDates: [
      {
        id: 'sd-1',
        date: new Date('2024-06-15'),
        service: 'Annual Gala Dinner - 100 guests',
        notes: 'Confirmed plated service',
      },
      {
        id: 'sd-2',
        date: new Date('2024-07-10'),
        service: 'Executive Retreat - breakfast & dinners',
        notes: 'Special dietary considerations required',
      },
    ],
    notes: 'Excellent reviews. Offers wine pairing service. 48-hour cancellation policy.',
  },
  {
    id: 'vendor-2',
    name: 'Blooming Beauty Florals',
    category: 'florist',
    contactPerson: 'Jennifer Lee',
    email: 'jen@bloominbeauty.com',
    phone: '(555) 234-5678',
    website: 'www.bloominbeauty.com',
    serviceDates: [
      {
        id: 'sd-3',
        date: new Date('2024-06-15'),
        service: 'Gala Centerpieces - 20 tables + entrance arrangements',
        notes: 'Preferred color: gold and white',
      },
    ],
    notes: 'Lead time: 2 weeks minimum. Free delivery within 10 miles.',
  },
  {
    id: 'vendor-3',
    name: 'Grand Ballroom Events Venue',
    category: 'venue',
    contactPerson: 'Robert Thompson',
    email: 'bookings@grandevents.com',
    phone: '(555) 345-6789',
    website: 'www.grandevents.com',
    serviceDates: [
      {
        id: 'sd-4',
        date: new Date('2024-06-15'),
        service: 'Main ballroom rental 5 PM - midnight',
        notes: 'Includes setup/breakdown time. Parking for 150 cars.',
      },
    ],
    notes: 'Capacity: 300 people. Has in-house AV and lighting. Insurance required.',
  },
  {
    id: 'vendor-4',
    name: 'Premier Limo Service',
    category: 'transportation',
    contactPerson: 'Antonio Rossi',
    email: 'antonio@premierlimo.com',
    phone: '(555) 456-7890',
    website: 'www.premierlimo.com',
    serviceDates: [
      {
        id: 'sd-5',
        date: new Date('2024-06-15'),
        service: '5 limousines for VIP guests',
        notes: 'Pickup from hotel, coordinated timing',
      },
    ],
    notes: 'Professional drivers. Complimentary water and mints. Tips not included.',
  },
  {
    id: 'vendor-5',
    name: 'Lakeside Mountain Lodge',
    category: 'venue',
    contactPerson: 'Sarah Winters',
    email: 'reservations@lakesidelodge.com',
    phone: '(555) 567-8901',
    website: 'www.lakesidelodge.com',
    serviceDates: [
      {
        id: 'sd-6',
        date: new Date('2024-07-10'),
        service: 'Executive retreat - 2 days, 20 rooms',
        notes: 'All-inclusive package with meals and activities',
      },
    ],
    notes: 'Beautiful lake views. Team building activities available. 50% deposit required.',
  },
  {
    id: 'vendor-6',
    name: 'Elite Photography Studio',
    category: 'photography',
    contactPerson: 'Michelle Park',
    email: 'michelle@elitephoto.com',
    phone: '(555) 678-9012',
    website: 'www.elitephoto.com',
    serviceDates: [
      {
        id: 'sd-7',
        date: new Date('2024-06-15'),
        service: 'Event photography 4 PM - midnight (8 hours)',
        notes: 'Includes photographer + assistant. Edited digital files within 2 weeks.',
      },
    ],
    notes: 'Professional portraits available. Additional prints at cost.',
  },
  {
    id: 'vendor-7',
    name: 'Sound & Light Productions',
    category: 'audio-visual',
    contactPerson: 'James Wilson',
    email: 'james@soundlight.com',
    phone: '(555) 789-0123',
    website: 'www.soundlight.com',
    serviceDates: [
      {
        id: 'sd-8',
        date: new Date('2024-06-15'),
        service: 'Event AV system - DJ, lights, screens',
        notes: 'Setup 3 PM, breakdown 1 AM',
      },
    ],
    notes: 'State-of-the-art equipment. Can accommodate live streaming.',
  },
  {
    id: 'vendor-8',
    name: 'Executive Event Planning',
    category: 'event-planning',
    contactPerson: 'Victoria Chen',
    email: 'victoria@execplan.com',
    phone: '(555) 890-1234',
    website: 'www.execplan.com',
    serviceDates: [
      {
        id: 'sd-9',
        date: new Date('2024-06-15'),
        service: 'Full event coordination and management',
        notes: 'Day-of coordination, vendor management, timeline oversight',
      },
    ],
    notes: 'Flat fee or percentage of event budget. References available.',
  },
];

export const TASKS: Task[] = [
  // Daily tasks
  {
    id: 'task-1',
    title: 'Review executive schedule',
    description: 'Check calendar and upcoming commitments',
    category: 'daily',
    completed: false,
    dueDate: new Date('2024-05-16'),
    recurrence: 'daily',
    assignee: 'Partner',
  },
  {
    id: 'task-2',
    title: 'Process emails',
    description: 'Review and file all incoming emails',
    category: 'daily',
    completed: true,
    dueDate: new Date('2024-05-16'),
    recurrence: 'daily',
    assignee: 'Partner',
  },
  {
    id: 'task-3',
    title: 'Update project status board',
    description: 'Sync with team on project progress',
    category: 'daily',
    completed: false,
    dueDate: new Date('2024-05-16'),
    recurrence: 'daily',
    assignee: 'You',
  },
  {
    id: 'task-4',
    title: 'Prepare meeting agenda',
    description: 'Compile topics for afternoon standup',
    category: 'daily',
    completed: false,
    dueDate: new Date('2024-05-16'),
    recurrence: 'daily',
    assignee: 'You',
  },

  // Weekly tasks
  {
    id: 'task-5',
    title: 'Prepare weekly report',
    description: 'Compile metrics and accomplishments for the week',
    category: 'weekly',
    completed: true,
    dueDate: new Date('2024-05-17'),
    recurrence: 'weekly',
    assignee: 'You',
  },
  {
    id: 'task-6',
    title: 'Team lunch planning',
    description: 'Coordinate Friday team lunch reservation',
    category: 'weekly',
    completed: false,
    dueDate: new Date('2024-05-17'),
    recurrence: 'weekly',
    assignee: 'Partner',
  },
  {
    id: 'task-7',
    title: 'Review expense reports',
    description: 'Approve submitted expense reports from team',
    category: 'weekly',
    completed: false,
    dueDate: new Date('2024-05-17'),
    recurrence: 'weekly',
    assignee: 'You',
  },

  // Monthly tasks
  {
    id: 'task-8',
    title: 'Budget review',
    description: 'Monthly budget allocation review and planning',
    category: 'monthly',
    completed: false,
    dueDate: new Date('2024-05-31'),
    recurrence: 'monthly',
    assignee: 'You',
  },
  {
    id: 'task-9',
    title: 'Client outreach',
    description: 'Touch base with key clients and partners',
    category: 'monthly',
    completed: false,
    dueDate: new Date('2024-05-31'),
    recurrence: 'monthly',
    assignee: 'Partner',
  },
  {
    id: 'task-10',
    title: 'Performance reviews',
    description: 'Conduct one-on-ones with direct reports',
    category: 'monthly',
    completed: false,
    dueDate: new Date('2024-05-31'),
    recurrence: 'monthly',
    assignee: 'You',
  },
];
